services:
  - type: web
    name: chatterbox-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p $PORT chatterbox_backend.asgi:application
    envVars:
      - key: PORT
        value: 8000
